# Generated by Django 5.1.7 on 2025-03-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='price_per_yard',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
