# Generated by Django 5.1.7 on 2025-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0004_remove_fabric_category_remove_fabric_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricvariant',
            name='color_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
