# Generated by Django 5.1.7 on 2025-03-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0005_fabricvariant_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricvariant',
            name='available_yard',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
