# Generated by Django 5.1.7 on 2025-03-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='is_provisional',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='manufacture_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='selling_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
