# Generated by Django 5.1.6 on 2025-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_product', '0002_finishedproduct_is_provisional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
