# Generated by Django 5.1.7 on 2025-05-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_product', '0003_finishedproduct_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedproduct',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
