# Generated by Django 5.1.6 on 2025-04-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsession',
            name='total_packed_quantity',
            field=models.IntegerField(editable=False),
        ),
    ]
