# Generated by Django 5.1.7 on 2025-04-17 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_product', '0003_finishedproduct_available_quantity'),
        ('packing_app', '0003_remove_packingsession_total_packed_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingsession',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_sessions', to='finished_product.finishedproduct'),
        ),
    ]
