# Generated by Django 5.1.7 on 2025-03-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0005_fabricvariant_color_name'),
        ('sewing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysewingrecord',
            name='fabric_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sewing_records', to='fabric.fabricvariant'),
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='fabric_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_product', to='fabric.fabricvariant'),
        ),
    ]
