# Generated by Django 5.1.6 on 2025-04-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sewing', '0003_remove_dailysewingrecord_fabric_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysewingrecord',
            old_name='cutting_detail',
            new_name='_cuttingrecordfabric',
        ),
    ]
