# Generated by Django 5.1.6 on 2025-04-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0003_cuttingrecord_product_name'),
        ('sewing', '0006_remove_dailysewingrecord_cutting_record_fabric'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysewingrecord',
            name='cutting_record_fabric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_sewing_records', to='cutting.cuttingrecordfabric'),
            preserve_default=False,
        ),
    ]
