# Generated by Django 5.1.7 on 2025-05-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_amount_paid_remove_order_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direct_sale',
            field=models.BooleanField(default=False),
        ),
    ]
