# Generated by Django 5.2.1 on 2025-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0003_cuttingrecord_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingrecord',
            name='fabric_definition',
        ),
    ]
