# Generated by Django 4.2.7 on 2025-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0004_remove_fabric_definition_from_cutting_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingrecord',
            name='cutting_image',
            field=models.URLField(blank=True, help_text='URL of the cutting image', max_length=500, null=True),
        ),
    ]
