# Generated by Django 4.2.7 on 2025-07-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0005_cuttingrecord_cutting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingrecord',
            name='cutting_image',
        ),
    ]
